[build]
  command = "npm run build"
  publish = "dist"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://eocampaign1.com https://googleads.g.doubleclick.net https://www.googleadservices.com https://www.google.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://images.unsplash.com https://www.google-analytics.com https://www.googletagmanager.com https://googleads.g.doubleclick.net https://www.google.com https://www.google.co.in https://gallery.eousercontent.com; connect-src 'self' https://www.google-analytics.com https://stats.g.doubleclick.net https://script.google.com https://script.googleusercontent.com https://www.googletagmanager.com https://analytics.google.com https://www.google.com https://www.googleadservices.com; font-src 'self' https://fonts.gstatic.com https://gallery.eo.page; frame-src 'self' https://www.googletagmanager.com https://td.doubleclick.net;"

[[headers]]
  for = "/famous-food-in-pondicherry.pdf"
  [headers.values]
    X-Robots-Tag = "noindex"
